spring:
  cloud:
    config:
      server:
       git:
          default-label: master
          uri: https://github.com/jgpreetham/config.git
          search-paths:
          - config-data
    bus:
      enabled: true
      refresh:
        enabled: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: busrefresh
server:
  port: 8888